image: docker:latest

services:
  - docker:dind

stages:
  - build services

.build-template:
  stage: build services
  script:
    - docker build -t account-service $SERVICE_PATH

build account:
  extends: .build-template
  variables:
    SERVICE_PATH: ./account-service

build payment:
  extends: .build-template
  variables:
    SERVICE_PATH: ./payment-service

build credit:
  extends: .build-template
  variables:
    SERVICE_PATH: ./credit-service

build profile:
  extends: .build-template
  variables:
    SERVICE_PATH: ./profile-service        